# Generated by Django 2.0 on 2020-10-04 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fraction', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='成绩分数')),
                ('subject', models.CharField(max_length=50, verbose_name='科目')),
            ],
            options={
                'verbose_name': '成绩表',
                'permissions': (('view_achievement', 'Can view achievement'),),
            },
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=20, verbose_name='学生名称')),
                ('student_number', models.CharField(max_length=50, verbose_name='联系电话')),
                ('student_address', models.CharField(default='中国', max_length=200, null=True, verbose_name='联系地址')),
                ('student_date', models.DateField(default='1999-01-01', null=True, verbose_name='出生日期')),
            ],
            options={
                'verbose_name': '学生列表',
                'permissions': (('view_student', 'Can view student'),),
            },
        ),
        migrations.AddField(
            model_name='achievement',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student', verbose_name='学生ID'),
        ),
    ]
