# Generated by Django 4.2 on 2023-04-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="env",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("env_name", models.CharField(max_length=20, verbose_name="环境名称")),
                (
                    "env_name_zh",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="环境名称"
                    ),
                ),
            ],
        ),
    ]
